//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blood_Bank_Final.DataAccess
{
    using Blood_Bank_Final.DataAccess.Abstract;
    using System;
    using System.Collections.Generic;
    
    public partial class bloodDonor
    {
        public int DonorId { get; set; }
        public string DonorName { get; set; }
        public string BloodGroup { get; set; }
    }
}
